export const ActionTypes = {
  INCREASE_QT: "INCREASE_QT",
  DECREASE_QT: "DECREASE_QT",
  CLEAR_CART: "CLEAR_CART",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  GET_TOTAL: "GET_TOTAL",
  SET_PRODUCTS: "SET_PRODUCTS",
  FETCH_CART: "FETCH_CART",
};
